---
title: Ah Counter Report
output: 
  revealjs::revealjs_presentation:
    self_contained: false
    theme: night
    transition: slide
    incremental: true
    center: true
    slide_level: 3
    smart: false
    css: style.css
    reveal_plugins: ["chalkboard", "zoom", "notes"]
    reveal_options:
      width: 1280
      height: 720
      chalkboard:
        theme: blackboard
        toggleNotesButton: false
        toggleChalkboardButton: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.width = 9,
  fig.height = 5,
  # fig.asp = .3,
  out.width = "100%"
)

# measure the run time of the code
startTime <- Sys.time()

# load packages
if (!require(reshape2)) {install.packages("reshape2"); library(reshape2)}      # transforming table shape
if (!require(ggplot2)) {install.packages("ggplot2"); library(ggplot2)}         # for plotting the graph
if (!require(dplyr)) {install.packages("dplyr"); library(dplyr)} (dplyr)       # joining data
if (!require(gganimate)) {install.packages("gganimate"); library(gganimate)}   # animated plots
if (!require(magick)) {install.packages("magick"); library(magick)}            # save gganimate object



# ---------------------------------------------- ggplot theme ----------------------------------------------

# create custom ggplot theme
fontsize <- 13
mc_colours <- colorRampPalette(c("#615dad","#329cd7","#87d1bf","#fff9e0","#f9e3a9","#feb87b","#e76a68"))
back_colour <- "#222222" # colour of the presentation background
front_colour <- "#eeeeee" # make legend text the opposite of the background

martina_style2 <- function(base_size = fontsize) {
  theme_minimal(base_size = base_size) %+replace%
    theme(
      rect = element_rect(fill = "transparent", colour = NA),
      plot.background = element_rect(fill = back_colour, colour = back_colour),
      plot.title = element_blank(),
      plot.margin = unit(c(0,20,15,0), "pt"),
      panel.grid.minor = element_blank(),
      panel.grid.major = element_blank(),
      panel.border = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      axis.text = element_blank(),
      legend.position = "top",
      legend.text.align = 0,
      legend.title = element_blank(),
      legend.text = element_text(face="bold", colour = front_colour, size = rel(0.70)),
      legend.key = element_rect(fill = "transparent", colour = NA),
      legend.key.size = unit(1, "lines"),
      legend.background = element_rect(fill = "transparent", colour = NA),
      legend.box.spacing = unit(0, "pt"),
      # facet options
      strip.background = element_rect(fill = "#17252D", color = "#17252D"),
      strip.text = element_text(size = rel(0.85), face = "bold", color = "white", margin = margin(5,0,5,0))
    )
}

# set the custom theme as default
theme_set(martina_style2())

# language settings = set english as default option
Sys.setlocale("LC_ALL","English_United Kingdom")




# ---------------------------------------------- load data ----------------------------------------------

# load ah_counter file with filler word counts
ah_counter <- read.csv("ah_counter.csv", sep=";", stringsAsFactors = FALSE)

# transform table to long format
ah_melt <- melt(ah_counter, id.vars = "name", variable.name = "word", value.name = "count", na.rm = TRUE)

# calculate total count for each person and sort from largest to smallest, then create a combined column with name and total count
totals <- aggregate(ah_melt[,"count"], by = list(ah_melt$name), FUN = sum)
names(totals) <- c("name", "total")
totals <- arrange(totals, total)
totals$nc <- paste0(totals$name, " (", totals$total, ")")

# transform word and name to factors and set their order
ah_melt$word <- factor(ah_melt$word, levels = levels(ah_melt$word)[length(ah_melt$word):1])
ah_melt$name <- factor(ah_melt$name, levels = totals$name)

# extract names with 0 filler words
no_ah_names <- ah_counter[!(ah_counter$name %in% ah_melt$name),"name"]
shownames <- length(no_ah_names) > 0     # if the names vector has any names in it, then display the names

# aggregate counts by filler word and sort from largest count to smallest
top_words <- aggregate(ah_melt[, "count"], by = list(ah_melt$word), FUN = sum)
names(top_words) <- c("word", "count")
top_words$word <- as.character(top_words$word)
top_words <- arrange(top_words, desc(count))

```


# 
<!-- first slide with gif image -->

<div class="tenor-gif-embed" data-postid="5610192" data-share-method="host" data-width="100%" data-aspect-ratio="1.5"><a href="https://tenor.com/view/love-heart-rose-rose-petals-gif-5610192">Love Heart GIF</a> from <a href="https://tenor.com/search/love-gifs">Love GIFs</a></div><script type="text/javascript" async src="https://tenor.com/embed.js"></script>


<!-- second slide with total filler word count -->
# `r sum(top_words$count)`
total filler words


<!-- third slide - make top 5 filler words appear one by one -->
#

```{r, results='asis'}
  cat("\n")
  cat("<section style=")
  cat('"')
  cat("font-size:6em;font-weight:900")
  cat('"')
  cat(">")
  cat("\n")
for(i in 1:5){
  cat("<span class=")
  cat('"')
  cat("fragment")
  cat('"')
  cat(" data-fragment-index=")
  cat('"')
  cat(i)
  cat('"')
  cat(">")
  cat(top_words$word[i])
  cat("</span>")
  cat("\n")
}
cat("</section>")
cat("\n")
```

<!-- fourth slide with gif image -->
# 

<div class="tenor-gif-embed" data-postid="4883358" data-share-method="host" data-width="100%" data-aspect-ratio="1.7857142857142858"><a href="https://tenor.com/view/black-cat-filing-nails-salem-gif-4883358">Black Cat GIF</a> from <a href="https://tenor.com/search/black-gifs">Black GIFs</a></div><script type="text/javascript" async src="https://tenor.com/embed.js"></script>


<!-- fifth slide graph by name -->
#

```{r}
# create animated horizontal column plot
ah_results <- ggplot(ah_melt) + geom_col(mapping = aes(count, name, fill=word), colour = back_colour, size = 3.5, width = .85) +
  geom_text(totals, mapping = aes(total, name, label = nc), colour = front_colour, fontface = "bold", nudge_x = 1.5, size = 3.2) +
  geom_text(ah_melt, mapping = aes(count, name, label = count), position = position_stack(vjust = 0.5), fontface = "bold", size = 2.5) +
  scale_fill_manual(values = mc_colours(length(unique(ah_melt$word)))) + guides(fill = guide_legend(nrow = 1, reverse = TRUE)) +
  transition_states(name, wrap = FALSE) +
  ease_aes('cubic-in-out') + shadow_mark() + enter_fade()

# anomate plot with magick%renderer
animate(ah_results, nframes = 50, fps = 4, renderer = magick_renderer(loop = FALSE))
```


<!-- slides with names of people with 0 filler words - only show if shownames condition defined earlier is TRUE -->
```{r, results='asis', eval=shownames}
for(i in no_ah_names){
  cat("\n")
  cat("###", i) # Create second level headings with the names.
  cat(" {center=true}")
  cat("\n")
}
```


<!-- hats-off gif slide -->
# {data-background="https://i.pinimg.com/originals/a4/fc/47/a4fc47c79788e60021926ac77fbbb2a4.gif"}


<!-- slide with rules to follow - appearing in order defined by index -->
#

<p style="font-size:50px" class="fragment visible" data-fragment-index="1">understand when you use filler words</p>
<br>
<p style="font-size:50px" class="fragment visible" data-fragment-index="3">breathe</p>
<br>
<p style="font-size:50px" class="fragment visible" data-fragment-index="2">embrace the pause</p>


<!-- last gif slide - congratulations! -->
# 

<div class="tenor-gif-embed" data-postid="6217699" data-share-method="host" data-width="100%" data-aspect-ratio="1.3184713375796178"><a href="https://tenor.com/view/friends-phoebe-rachel-excited-gif-6217699">Friends Phoebe GIF</a> from <a href="https://tenor.com/search/friends-gifs">Friends GIFs</a></div><script type="text/javascript" async src="https://tenor.com/embed.js"></script>




```{r, include=FALSE}
# check the run time ---> it can take between 1 to 3 minutes
endTime <- Sys.time()
endTime - startTime
```
